apiVersion: v1
kind: Service
metadata:
  name: forkline-service
spec:
  selector:
    app: forkline-api
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090         
  type: NodePort